#!/usr/bin/env bash
# Bash script that will display information about subdomains.

function audit_subdomain() {
  local domain="$1"
  local subdomain="$2"

  if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    record=$(dig +short "$sub.$domain" | awk '{ print $1 }')
    type=$(dig "$sub.$domain" | awk '$3 == "IN" { print $4 }')
    echo "The subdomain $sub is a $type record and points to $record"
  done
}

audit_subdomain "$1" "$2"
